from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1024, 700)

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")

        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")

        self.header_widget = QtWidgets.QWidget(self.widget_3)
        self.header_widget.setMinimumSize(QtCore.QSize(0, 40))
        self.header_widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.header_widget.setObjectName("header_widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.change_btn = QtWidgets.QPushButton(self.header_widget)
        self.change_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.change_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-96-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/arrow-31-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.change_btn.setIcon(icon)
        self.change_btn.setCheckable(True)
        self.change_btn.setObjectName("change_btn")
        self.horizontalLayout_4.addWidget(self.change_btn)
        spacerItem = QtWidgets.QSpacerItem(156, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(8)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_input = QtWidgets.QLineEdit(self.header_widget)
        self.search_input.setObjectName("search_input")
        self.horizontalLayout_3.addWidget(self.search_input)
        self.search_btn = QtWidgets.QPushButton(self.header_widget)
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_btn.setText("")
        search_icon = QtGui.QIcon()
        search_icon.addPixmap(QtGui.QPixmap(":/icon/icon/search-3-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(search_icon)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout_3.addWidget(self.search_btn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(155, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)

        self.user_btn = QtWidgets.QPushButton(self.header_widget)
        self.user_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_btn.setText("")
        user_icon = QtGui.QIcon()
        user_icon.addPixmap(QtGui.QPixmap(":/icon/icon/x-mark-4-32.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(user_icon)
        self.user_btn.setIconSize(QtCore.QSize(20, 20))
        self.user_btn.setCheckable(True)
        self.user_btn.setChecked(False)
        self.user_btn.setAutoExclusive(True)
        self.user_btn.setObjectName("user_btn")
        self.horizontalLayout_4.addWidget(self.user_btn)

        self.verticalLayout_5.addWidget(self.header_widget)

        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_3)
        self.stackedWidget.setObjectName("stackedWidget")

        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.home_page)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget = QtWidgets.QWidget(self.home_page)
        self.widget.setObjectName("widget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.image_label = QtWidgets.QLabel(self.widget)
        self.image_label.setObjectName("image_label")
        self.image_label.setPixmap(QtGui.QPixmap(":/icon/icon/user-48.png"))  # Set the image here
        self.verticalLayout_7.addWidget(self.image_label)
        self.verticalLayout_7.addWidget(self.widget)
        self.gridLayout_2.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.home_page)

        self.trade_page = QtWidgets.QWidget()
        self.trade_page.setObjectName("trade_page")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.trade_page)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_2 = QtWidgets.QWidget(self.trade_page)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_8.addWidget(self.label_3)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.trade_page)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(0)
        self.tableWidget_2.setRowCount(0)
        self.verticalLayout_9.addWidget(self.tableWidget_2)
        self.gridLayout_3.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.trade_page)

        self.order_page = QtWidgets.QWidget()
        self.order_page.setObjectName("order_page")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.order_page)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_4 = QtWidgets.QWidget(self.order_page)
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.verticalLayout_11.addWidget(self.widget_4)
        self.tableWidget_3 = QtWidgets.QTableWidget(self.order_page)
        self.tableWidget_3.setAutoFillBackground(True)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(0)
        self.tableWidget_3.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tableWidget_3)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.order_page)

        self.history_page = QtWidgets.QWidget()
        self.history_page.setObjectName("history_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.history_page)
        self.gridLayout_5.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.widget_5 = QtWidgets.QWidget(self.history_page)
        self.widget_5.setObjectName("widget_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_5)
        self.verticalLayout_11.addWidget(self.widget_5)
        self.tableWidget_4 = QtWidgets.QTableWidget(self.history_page)
        self.tableWidget_4.setAutoFillBackground(True)
        self.tableWidget_4.setObjectName("tableWidget_3")
        self.tableWidget_4.setColumnCount(0)
        self.tableWidget_4.setRowCount(0)
        self.verticalLayout_11.addWidget(self.tableWidget_4)
        self.gridLayout_5.addLayout(self.verticalLayout_11, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.history_page)

        self.search_page = QtWidgets.QWidget()
        self.search_page.setObjectName("search_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.search_page)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_7 = QtWidgets.QLabel(self.search_page)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.search_page)
        self.user_detail = QtWidgets.QWidget()
        self.user_detail.setObjectName("user_detail")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.user_detail)
        self.gridLayout_6.setObjectName("gridLayout_6")

        self.label_8 = QtWidgets.QLabel(self.user_detail)
        self.label_8.setObjectName("label_8")
        self.gridLayout_6.addWidget(self.label_8, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.user_detail)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)

        self.icon_only_widget = QtWidgets.QWidget(self.centralwidget)
        self.icon_only_widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.icon_only_widget.setObjectName("icon_only_widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.icon_only_widget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.icon_only_widget)
        self.label.setMinimumSize(QtCore.QSize(30, 30))
        self.label.setMaximumSize(QtCore.QSize(30, 30))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icon/icon/user-48.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")

        self.home_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.home_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_1.setText("")
        home_icon = QtGui.QIcon()
        home_icon.addPixmap(QtGui.QPixmap(":/icon/icon/home2.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.home_btn_1.setIcon(home_icon)
        self.home_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.home_btn_1.setCheckable(True)
        self.home_btn_1.setAutoRepeat(False)
        self.home_btn_1.setAutoExclusive(True)
        self.home_btn_1.setObjectName("home_btn_1")
        self.verticalLayout.addWidget(self.home_btn_1)

        self.trade_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.trade_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trade_btn_1.setText("")
        trade_icon = QtGui.QIcon()
        trade_icon.addPixmap(QtGui.QPixmap(":/icon/icon/transaction-14830.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.trade_btn_1.setIcon(trade_icon)
        self.trade_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.trade_btn_1.setCheckable(True)
        self.trade_btn_1.setAutoRepeat(False)
        self.trade_btn_1.setAutoExclusive(True)
        self.trade_btn_1.setObjectName("trade_btn_1")
        self.verticalLayout.addWidget(self.trade_btn_1)

        self.order_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.order_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.order_btn_1.setText("")
        order_icon = QtGui.QIcon()
        order_icon.addPixmap(QtGui.QPixmap(":/icon/icon/packaging-product-14475.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.order_btn_1.setIcon(order_icon)
        self.order_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.order_btn_1.setCheckable(True)
        self.order_btn_1.setAutoRepeat(False)
        self.order_btn_1.setAutoExclusive(True)
        self.order_btn_1.setObjectName("order_btn_1")
        self.verticalLayout.addWidget(self.order_btn_1)

        self.history_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.history_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn_1.setText("")
        history_icon = QtGui.QIcon()
        history_icon.addPixmap(QtGui.QPixmap(":/icon/icon/history_icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.history_btn_1.setIcon(history_icon)
        self.history_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.history_btn_1.setCheckable(True)
        self.history_btn_1.setAutoRepeat(False)
        self.history_btn_1.setAutoExclusive(True)
        self.history_btn_1.setObjectName("history_btn_1")
        self.verticalLayout.addWidget(self.history_btn_1)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        spacerItem2 = QtWidgets.QSpacerItem(50, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)

        self.exit_btn_1 = QtWidgets.QPushButton(self.icon_only_widget)
        self.exit_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn_1.setText("")
        exit_icon = QtGui.QIcon()
        exit_icon.addPixmap(QtGui.QPixmap(":/icon/icon/x-mark-4-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_btn_1.setIcon(exit_icon)
        self.exit_btn_1.setIconSize(QtCore.QSize(20, 20))
        self.exit_btn_1.setCheckable(True)
        self.exit_btn_1.setAutoExclusive(True)
        self.exit_btn_1.setObjectName("exit_btn_1")
        self.verticalLayout_3.addWidget(self.exit_btn_1)
        self.gridLayout.addWidget(self.icon_only_widget, 0, 0, 1, 1)

        self.full_menu_widget = QtWidgets.QWidget(self.centralwidget)
        self.full_menu_widget.setMaximumSize(QtCore.QSize(500, 16777215))
        self.full_menu_widget.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.full_menu_widget.setObjectName("full_menu_widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.full_menu_widget)
        self.verticalLayout_4.setContentsMargins(0, 0, 20, 0)
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.logo_label_2 = QtWidgets.QLabel(self.full_menu_widget)
        self.logo_label_2.setMinimumSize(QtCore.QSize(30, 30))
        self.logo_label_2.setMaximumSize(QtCore.QSize(30, 30))
        self.logo_label_2.setText("")
        self.logo_label_2.setPixmap(QtGui.QPixmap(":/icon/icon/user-48.png"))
        self.logo_label_2.setScaledContents(True)
        self.logo_label_2.setObjectName("logo_label_2")
        self.horizontalLayout.addWidget(self.logo_label_2)

        self.logo_label_3 = QtWidgets.QLabel(self.full_menu_widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.logo_label_3.setFont(font)
        self.logo_label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label_3.setObjectName("logo_label_3")
        self.horizontalLayout.addWidget(self.logo_label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.home_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.home_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.home_btn_2.setIcon(home_icon)
        self.home_btn_2.setCheckable(True)
        self.home_btn_2.setAutoRepeat(False)
        self.home_btn_2.setAutoExclusive(True)
        self.home_btn_2.setObjectName("home_btn_2")
        self.home_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.home_btn_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalLayout_2.addWidget(self.home_btn_2)

        self.trade_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.trade_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trade_btn_2.setIcon(trade_icon)
        self.trade_btn_2.setCheckable(True)
        self.trade_btn_2.setAutoRepeat(False)
        self.trade_btn_2.setAutoExclusive(True)
        self.trade_btn_2.setObjectName("dashboard_btn_2")
        self.trade_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.trade_btn_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalLayout_2.addWidget(self.trade_btn_2)

        self.order_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.order_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.order_btn_2.setIcon(order_icon)
        self.order_btn_2.setCheckable(True)
        self.order_btn_2.setAutoRepeat(False)
        self.order_btn_2.setAutoExclusive(True)
        self.order_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.order_btn_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.order_btn_2.setObjectName("order_btn_2")
        self.verticalLayout_2.addWidget(self.order_btn_2)

        self.history_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.history_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.history_btn_2.setIcon(history_icon)
        self.history_btn_2.setCheckable(True)
        self.history_btn_2.setAutoRepeat(False)
        self.history_btn_2.setAutoExclusive(True)
        self.history_btn_2.setObjectName("history_btn_2")
        self.history_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.history_btn_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.verticalLayout_2.addWidget(self.history_btn_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)

        spacerItem3 = QtWidgets.QSpacerItem(20, 351, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)

        self.exit_btn_2 = QtWidgets.QPushButton(self.full_menu_widget)
        self.exit_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit_btn_2.setIcon(exit_icon)
        self.exit_btn_2.setCheckable(True)
        self.exit_btn_2.setAutoExclusive(True)
        self.exit_btn_2.setObjectName("exit_btn_2")
        self.exit_btn_2.setMinimumSize(QtCore.QSize(120, 0))
        self.exit_btn_2.setMaximumSize(QtCore.QSize(150, 16777215))
        self.verticalLayout_4.addWidget(self.exit_btn_2)
        self.gridLayout.addWidget(self.full_menu_widget, 0, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(4)
        self.change_btn.toggled['bool'].connect(self.icon_only_widget.setVisible) # type: ignore
        self.change_btn.toggled['bool'].connect(self.full_menu_widget.setHidden) # type: ignore

        self.home_btn_1.toggled['bool'].connect(self.home_btn_2.setChecked) # type: ignore
        self.trade_btn_1.toggled['bool'].connect(self.trade_btn_2.setChecked) # type: ignore
        self.order_btn_1.toggled['bool'].connect(self.order_btn_2.setChecked) # type: ignore
        self.history_btn_1.toggled['bool'].connect(self.history_btn_2.setChecked) # type: ignore
        self.exit_btn_1.toggled['bool'].connect(self.exit_btn_2.setChecked) # type: ignore
        self.home_btn_2.toggled['bool'].connect(self.home_btn_1.setChecked) # type: ignore
        self.trade_btn_2.toggled['bool'].connect(self.trade_btn_1.setChecked) # type: ignore
        self.order_btn_2.toggled['bool'].connect(self.order_btn_1.setChecked) # type: ignore
        self.history_btn_2.toggled['bool'].connect(self.history_btn_1.setChecked) # type: ignore
        self.exit_btn_2.toggled['bool'].connect(self.exit_btn_1.setChecked) # type: ignore
        self.exit_btn_1.clicked.connect(MainWindow.close) # type: ignore
        self.exit_btn_2.clicked.connect(MainWindow.close) # type: ignore
        self.search_btn.clicked.connect(self.label_7.show) # type: ignore
        self.user_btn.clicked.connect(self.label_8.show) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Search..."))
        # self.label_2.setText(_translate("MainWindow", "Home Table"))
        self.label_3.setText(_translate("MainWindow", "Trade Table"))
        self.label_4.setText(_translate("MainWindow", "Order Table"))
        self.label_5.setText(_translate("MainWindow", "History Table"))
        self.label_7.setText(_translate("MainWindow", "Search page"))
        self.label_8.setText(_translate("MainWindow", "User detail page"))
        self.logo_label_3.setText(_translate("MainWindow", "Sidebar"))
        self.home_btn_2.setText(_translate("MainWindow", "Home"))
        self.trade_btn_2.setText(_translate("MainWindow", "Trades"))
        self.order_btn_2.setText(_translate("MainWindow", "Orders"))
        self.history_btn_2.setText(_translate("MainWindow", "History"))
        self.exit_btn_2.setText(_translate("MainWindow", "Exit"))

import resource_rc
